version: 2
jobs:
  test:
    resource_class: medium
    docker:
    - image: circleci/android:api-28
    environment:
      _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
    steps:
    - checkout
    - restore_cache:
        keys:
        - gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
        - gradle-

    - restore_cache:
        key: android-cache-

    - run:
        name: Start Gradle Daemon
        command: nohup ./gradlew

    - run:
        name: Build and test Project
        command: ./gradlew test

    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

    - save_cache:
        key: android-cache-{{ epoch }}
        paths:
        - ~/.android/build-cache
        - ~/.android/cache

  checks:
    resource_class: large
    docker:
    - image: circleci/android:api-28
    steps:
    - checkout
    - restore_cache:
        keys:
        - gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
        - gradle-

    - run:
        name: Run Quality Checks
        command: ./gradlew ktlint

    - store_artifacts:
        path: app/build/reports
        destination: Test Reports
    - store_test_results:
        path: build/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
    - test
    - checks